name: CI - test
on:
   push:
     branches:
       - test
   workflow_dispatch:
     inputs:
       environment:
         description: 'Docker image tag'
         default: test
         required: false
       tag:
         description: 'Deploy to test env ?'
         required: false
         type: boolean
jobs:
  inputs-value:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Tags: $TAG"
          echo "Environment: $ENVIRONMENT"
        env:
          TAG: ${{ github.event.inputs.tag }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
   
